In [4]:
#Imports
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
#Base de treino
df = pd.read_csv('df_treino_m6.csv', sep = ';')
#Visualização
df.head(2)

C:\Users\henrique.zaidan\AppData\Local\Temp\ipykernel_17980\4274147872.py:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_treino_m6.csv', sep = ';')

,num_adm,idade,ag_tempo_base,ag_valor,ag_tipo_cliente,ag_velocidade,meses_base_ultimo_plano,meses_base_cadastro,valor,empresa,...,safra,cluster_perc_pago,cluster_total_pago,cluster_os,cluster_protocolos,cluster_bloqueio,cluster_atraso,pontuacao,cluster,ALVO
0,3175910.0,69.0,g_<=36meses,b_<=R$100,pessoa_fisica,a_<=200MB,36.0,36.0,99.90,DSN,...,202212,2.0,2.0,4.0,4.0,3.0,1.0,16.0,Baixo Valor,0
1,843310.0,34.0,a_<=3meses,c_<=R$120,pessoa_fisica,c_<=650MB,0.0,97.0,116.99,DSN,...,202301,4.0,3.0,4.0,4.0,4.0,1.0,20.0,Médio Valor,0

In [6]:
# 3. Amostragem estratificada (5.000 observações)
n_amostra = 5000
amostra, _ = train_test_split(
    df,
    train_size=n_amostra,
    stratify=df['ALVO'],  # Mantém a proporção do ALVO
    random_state=42
)

In [7]:
amostra.head(3)

,num_adm,idade,ag_tempo_base,ag_valor,ag_tipo_cliente,ag_velocidade,meses_base_ultimo_plano,meses_base_cadastro,valor,empresa,...,safra,cluster_perc_pago,cluster_total_pago,cluster_os,cluster_protocolos,cluster_bloqueio,cluster_atraso,pontuacao,cluster,ALVO
105167,5270240.0,30.0,f_<=24meses,a_<=R$80,pessoa_fisica,a_<=200MB,16.0,16.0,79.9,DSN,...,202212,4.0,1.0,4.0,4.0,3.0,3.0,19.0,Médio Valor,0
111036,5630150.0,32.0,f_<=24meses,e_>R$120,pessoa_fisica,c_<=650MB,15.0,15.0,129.9,DSN,...,202301,2.0,2.0,4.0,4.0,3.0,1.0,16.0,Baixo Valor,0
97830,4193190.0,54.0,f_<=24meses,e_>R$120,pessoa_fisica,c_<=650MB,24.0,24.0,129.9,DSN,...,202301,2.0,2.0,4.0,4.0,2.0,1.0,15.0,Baixo Valor,0

In [8]:
# 5. Resultado (opcional: salvar em CSV)
amostra.to_csv('amostra_estratificada.csv', index=False)